<a href="https://colab.research.google.com/github/OuhmadMohamed/DI_Bootcamp/blob/main/Week5/Day2/ExercisesXP_W5_D2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises XP — NumPy, Pandas, and Matplotlib Solutions

Exercise 1: Matrix Operations

In [ ]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [4, 1, 8]
])

print("Matrix:")
print(matrix)

# Determinant
det = np.linalg.det(matrix)
print("\nDeterminant:")
print(det)

# Inverse
if det != 0:
    inverse = np.linalg.inv(matrix)
    print("\nInverse:")
    print(inverse)
else:
    print("Matrix is not invertible.")

Matrix:
[[2 1 3]
 [1 0 2]
 [4 1 8]]

Determinant:
-1.0

Inverse:
[[ 2.  5. -2.]
 [ 0. -4.  1.]
 [-1. -2.  1.]]


Explanation
* np.linalg.det() calculates the determinant.
* np.linalg.inv() calculates the inverse if the determinant is not zero.

Exercise 2: Statistical Analysis

In [ ]:
import numpy as np

# Generate 50 random numbers
data = np.random.rand(50)

# Mean
mean = np.mean(data)

# Median
median = np.median(data)

# Standard deviation
std_dev = np.std(data)

print("data:", data)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

data: [0.68149496 0.99759222 0.63466684 0.44087455 0.93275852 0.44875651
 0.77983896 0.72337503 0.08461847 0.7025191  0.81875618 0.85372196
 0.09365312 0.56297635 0.34129325 0.74528914 0.18262655 0.33439773
 0.37529532 0.99336985 0.02918246 0.63757204 0.92925254 0.1772742
 0.16179512 0.95752029 0.41981143 0.91116658 0.67762889 0.9601862
 0.24586132 0.65221166 0.78987604 0.00772435 0.77308633 0.68585392
 0.20293143 0.58580335 0.76940423 0.83197893 0.71202564 0.0635686
 0.32480849 0.42129913 0.43171964 0.48452599 0.60251172 0.05636028
 0.36109911 0.5764106 ]
Mean: 0.5433665025121586
Median: 0.5941575364147555
Standard Deviation: 0.28951390302508045


Explanation
* Mean = average value.
* Median = middle value.
* Standard deviation = spread of data.

Exercise 3: Date Manipulation

In [ ]:
import numpy as np

# January 2023 dates
dates = np.arange(
    np.datetime64('2023-01-01'),
    np.datetime64('2023-02-01')
)

print("Original Dates:")
print(dates)

# Convert format YYYY/MM/DD
formatted_dates = np.datetime_as_string(
    dates,
    unit='D'
)

formatted_dates = np.char.replace(
    formatted_dates,
    '-',
    '/'
)

print("\nFormatted Dates:")
print(formatted_dates)

Original Dates:
['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09' '2023-01-10'
 '2023-01-11' '2023-01-12' '2023-01-13' '2023-01-14' '2023-01-15'
 '2023-01-16' '2023-01-17' '2023-01-18' '2023-01-19' '2023-01-20'
 '2023-01-21' '2023-01-22' '2023-01-23' '2023-01-24' '2023-01-25'
 '2023-01-26' '2023-01-27' '2023-01-28' '2023-01-29' '2023-01-30'
 '2023-01-31']

Formatted Dates:
['2023/01/01' '2023/01/02' '2023/01/03' '2023/01/04' '2023/01/05'
 '2023/01/06' '2023/01/07' '2023/01/08' '2023/01/09' '2023/01/10'
 '2023/01/11' '2023/01/12' '2023/01/13' '2023/01/14' '2023/01/15'
 '2023/01/16' '2023/01/17' '2023/01/18' '2023/01/19' '2023/01/20'
 '2023/01/21' '2023/01/22' '2023/01/23' '2023/01/24' '2023/01/25'
 '2023/01/26' '2023/01/27' '2023/01/28' '2023/01/29' '2023/01/30'
 '2023/01/31']


Exercise 4: Data Manipulation with NumPy and Pandas

In [ ]:
import numpy as np
import pandas as pd

# DataFrame with random values
df = pd.DataFrame(
    np.random.randint(1, 100, (10, 3)),
    columns=['A', 'B', 'C']
)

print(df)

    A   B   C
0  16  29   4
1   8  53  52
2  81  78  77
3  62  84   1
4  21  88  16
5  30   6  91
6  37  92  35
7  10  56  21
8  11  89  12
9  47  79  74


In [ ]:
#Conditional Selection
print("\nValues in column A > 50:")
print(df[df['A'] > 50])
#Aggregation
print("\nColumn Sums:")
print(df.sum())

print("\nColumn Means:")
print(df.mean())


Values in column A > 50:
    A   B   C
2  81  78  77
3  62  84   1

Column Sums:
A    323
B    654
C    383
dtype: int64

Column Means:
A    32.3
B    65.4
C    38.3
dtype: float64


Exercise 5: Image Representation

Explanation

A grayscale image is represented as a 2D NumPy array:

* Each element = pixel.
* Value range: 0 = black; 255 = white

In [ ]:
import numpy as np

image = np.array([
    [0, 50, 100, 150, 200],
    [20, 70, 120, 170, 220],
    [40, 90, 140, 190, 240],
    [60, 110, 160, 210, 255],
    [80, 130, 180, 230, 255]
])

print(image)

[[  0  50 100 150 200]
 [ 20  70 120 170 220]
 [ 40  90 140 190 240]
 [ 60 110 160 210 255]
 [ 80 130 180 230 255]]


Exercise 6: Basic Hypothesis Testing

In [ ]:
import numpy as np

# Productivity before training
productivity_before = np.random.normal(
    loc=50,
    scale=10,
    size=30
)

# Productivity after training
productivity_after = productivity_before + np.random.normal(
    loc=5,
    scale=3,
    size=30
)

Hypotheses

* Null Hypothesis (H₀)
Training does not improve productivity.
Mean After ≤ Mean Before

* Alternative Hypothesis (H₁)
Training improves productivity.
Mean After > Mean Before

In [ ]:
#Test
mean_before = np.mean(productivity_before)
mean_after = np.mean(productivity_after)

print("Mean Before:", mean_before)
print("Mean After:", mean_after)

difference = mean_after - mean_before

print("Average Improvement:", difference)

if difference > 0:
    print("Evidence suggests productivity improved.")
else:
    print("No evidence of improvement.")

Mean Before: 45.74674732712645
Mean After: 50.71226231765437
Average Improvement: 4.965514990527922
Evidence suggests productivity improved.


Exercise 7: Complex Array Comparison

In [ ]:
import numpy as np

array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([5, 25, 25, 45, 40])

comparison = array1 > array2

print(comparison)

[ True False  True False  True]


Exercise 8: Time Series Data Manipulation

In [ ]:
import numpy as np

dates = np.arange(
    np.datetime64('2023-01-01'),
    np.datetime64('2024-01-01')
)

In [ ]:
#January–March
q1 = dates[
    (dates >= '2023-01-01') &
    (dates < '2023-04-01')
]

print(q1)

In [ ]:

#April–June
q2 = dates[
    (dates >= '2023-04-01') &
    (dates < '2023-07-01')
]

print(q2)
#July–September
q3 = dates[
    (dates >= '2023-07-01') &
    (dates < '2023-10-01')
]

print(q3)
#October–December
q4 = dates[
    (dates >= '2023-10-01') &
    (dates < '2024-01-01')
]

print(q4)

Exercise 9: Data Conversion


In [ ]:
#NumPy → Pandas
import numpy as np
import pandas as pd

array = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

df = pd.DataFrame(
    array,
    columns=['A', 'B']
)

print(df)

In [ ]:
#Pandas → NumPy
new_array = df.to_numpy()

print(new_array)

Exercise 10: Basic Visualization


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Generate data
data = np.random.randint(
    1,
    100,
    20
)

# Plot
plt.figure(figsize=(8,5))

plt.plot(
    data,
    marker='o'
)

plt.title("Random Numbers Line Graph")
plt.xlabel("Index")
plt.ylabel("Value")

plt.grid(True)

plt.show()

Explanation
* plt.plot() creates a line chart.
* marker='o' displays points.
* grid(True) improves readability.